-- 코드를 입력하세요
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) SCORE
FROM REST_INFO RI
JOIN REST_REVIEW R ON R.REST_ID	= RI.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID
ORDER BY ROUND(AVG(R.REVIEW_SCORE),2) DESC, RI.FAVORITES DESC;